import AppKit
import SwiftUI

class BrandAssets {
    static let shared = BrandAssets()

    let claudeRaw: NSImage?
    let codexRaw: NSImage?

    let claudeIcon14: NSImage?
    let codexIcon14: NSImage?
    let claudeIcon20: NSImage?
    let codexIcon20: NSImage?

    /// The app icon artwork (rounded square with the dial) for in-app use.
    let appIcon: NSImage?

    /// Menu bar glyphs generated by `scripts/generate_icon.swift`.
    /// `runwayGlyph` is a template so it follows the menu bar text color;
    /// `runwayWarningGlyph` keeps its amber-red color.
    let runwayGlyph: NSImage?
    let runwayWarningGlyph: NSImage?

    static let menuBarGlyphPointSize: CGFloat = 16

    private init() {
        let claude = Self.loadRawImage(named: "claude_logo") ?? Self.loadRawImage(named: "claude")
        let codex = Self.loadRawImage(named: "openai_logo") ?? Self.loadRawImage(named: "codex")

        self.claudeRaw = claude
        self.codexRaw = codex

        self.claudeIcon14 = claude.map { Self.resizeImage($0, targetSize: NSSize(width: 14, height: 14)) }
        self.codexIcon14 = codex.map { Self.resizeImage($0, targetSize: NSSize(width: 14, height: 14)) }
        self.claudeIcon20 = claude.map { Self.resizeImage($0, targetSize: NSSize(width: 20, height: 20)) }
        self.codexIcon20 = codex.map { Self.resizeImage($0, targetSize: NSSize(width: 20, height: 20)) }

        // The OpenAI mark is white-on-transparent. As a template it follows the
        // current foreground color, so it stays visible in light mode too.
        for image in [codexRaw, codexIcon14, codexIcon20].compactMap({ $0 }) {
            image.isTemplate = true
        }

        self.appIcon = Self.loadRawImage(named: "appicon")

        // The glyph PNGs are 64 px; sized to 16 pt they render as high-resolution.
        let glyphSize = NSSize(width: Self.menuBarGlyphPointSize, height: Self.menuBarGlyphPointSize)
        self.runwayGlyph = Self.loadRawImage(named: "menubar_glyph").map { image in
            image.size = glyphSize
            image.isTemplate = true
            return image
        }
        self.runwayWarningGlyph = Self.loadRawImage(named: "menubar_glyph_warning").map { image in
            image.size = glyphSize
            return image
        }
    }

    private static func loadRawImage(named name: String) -> NSImage? {
        // 1. Try Bundle.main resource
        if let path = Bundle.main.path(forResource: name, ofType: "png"),
           let img = NSImage(contentsOfFile: path) {
            return img
        }

        // 2. Try current directory assets/ (swift test, swift run)
        let currentDirPath = FileManager.default.currentDirectoryPath + "/assets/\(name).png"
        if FileManager.default.fileExists(atPath: currentDirPath),
           let img = NSImage(contentsOfFile: currentDirPath) {
            return img
        }

        return nil
    }

    static func resizeImage(_ image: NSImage, targetSize: NSSize) -> NSImage {
        guard targetSize.width > 0 && targetSize.height > 0 && image.size.width > 0 && image.size.height > 0 else {
            return image
        }
        let newImage = NSImage(size: targetSize)
        newImage.lockFocus()
        NSGraphicsContext.current?.imageInterpolation = .high
        image.draw(
            in: NSRect(origin: .zero, size: targetSize),
            from: NSRect(origin: .zero, size: image.size),
            operation: .copy,
            fraction: 1.0
        )
        newImage.unlockFocus()
        return newImage
    }

    // MARK: - Menu Bar Rendering

    private static let boltSymbol: NSImage? = {
        let config = NSImage.SymbolConfiguration(pointSize: 11, weight: .bold)
        return NSImage(systemSymbolName: "bolt.fill", accessibilityDescription: "RunwayLeft")?
            .withSymbolConfiguration(config)
    }()

    /// LiteLLM has no bundled logo; a network symbol stands in, tinted like text.
    static let litellmSymbol: NSImage? = {
        let config = NSImage.SymbolConfiguration(pointSize: 11, weight: .semibold)
        return NSImage(systemSymbolName: "point.3.connected.trianglepath.dotted", accessibilityDescription: "LiteLLM")?
            .withSymbolConfiguration(config)
    }()

    private func image(for icon: MenuBarSegment.Icon, alert: StatusLevel?) -> NSImage? {
        switch icon {
        case .app:
            if alert?.isProblem == true, let warning = runwayWarningGlyph {
                return warning
            }
            return runwayGlyph ?? Self.boltSymbol
        case .claude: return claudeRaw
        case .codex: return codexRaw
        case .litellm: return Self.litellmSymbol
        case .none: return nil
        }
    }

    /// Height of each icon in the menu bar image. The app glyph is drawn a
    /// little larger than the provider logos so the runway stays legible.
    private func iconHeight(for icon: MenuBarSegment.Icon) -> CGFloat {
        icon == .app ? Self.menuBarGlyphPointSize : 13.0
    }

    private static func alertColor(for level: StatusLevel) -> NSColor {
        switch level {
        case .majorOutage, .partialOutage: return .systemRed
        case .degraded: return .systemOrange
        case .maintenance: return .systemBlue
        default: return .clear
        }
    }

    /// Renders the composed segments into a single image suitable for
    /// `MenuBarExtra`. Segments carrying an alert are outlined in the alert
    /// color so a provider outage is visible at a glance.
    func createMenuBarImage(segments: [MenuBarSegment]) -> NSImage {
        let font = NSFont.monospacedDigitSystemFont(ofSize: 11.5, weight: .bold)
        let iconTextGap: CGFloat = 3.5
        let segmentGap: CGFloat = 8.0
        let height: CGFloat = 18.0
        let outlinePadding: CGFloat = 4.0
        let outlineRadius: CGFloat = 4.5

        let textAttrs: [NSAttributedString.Key: Any] = [
            .font: font,
            .foregroundColor: NSColor.labelColor
        ]

        struct Placed {
            let image: NSImage?
            /// Monochrome marks (app glyph, OpenAI) are tinted with the label color.
            let tinted: Bool
            let imageSize: NSSize
            let text: String
            let textSize: NSSize
            let alert: StatusLevel?
            /// Where the (optional) outline starts and how wide it is.
            let outlineX: CGFloat
            let outlineWidth: CGFloat
            /// Where the icon/text content starts.
            let contentX: CGFloat
        }

        var placed: [Placed] = []
        var cursor: CGFloat = 0

        for (index, segment) in segments.enumerated() {
            if index > 0 {
                cursor += segmentGap
            }

            var imageSize = NSSize.zero
            let img = image(for: segment.icon, alert: segment.alert)
            if let img = img, img.size.width > 0 && img.size.height > 0 {
                let aspect = img.size.width / max(1.0, img.size.height)
                let iconSize = iconHeight(for: segment.icon)
                imageSize = NSSize(width: max(1.0, iconSize * aspect), height: iconSize)
            }

            var textSize = NSSize.zero
            if !segment.text.isEmpty {
                textSize = (segment.text as NSString).size(withAttributes: textAttrs)
            }

            var contentWidth = imageSize.width + textSize.width
            if imageSize.width > 0 && textSize.width > 0 {
                contentWidth += iconTextGap
            }

            let padding = segment.alert != nil ? outlinePadding : 0
            let outlineX = cursor
            let contentX = cursor + padding
            let outlineWidth = contentWidth + padding * 2
            cursor = outlineX + outlineWidth

            // The warning glyph carries its own color; everything else monochrome is tinted.
            let usesWarningArt = segment.icon == .app && segment.alert?.isProblem == true && runwayWarningGlyph != nil
            let tinted = (segment.icon == .app || segment.icon == .codex || segment.icon == .litellm) && !usesWarningArt

            placed.append(Placed(
                image: img,
                tinted: tinted,
                imageSize: imageSize,
                text: segment.text,
                textSize: textSize,
                alert: segment.alert,
                outlineX: outlineX,
                outlineWidth: outlineWidth,
                contentX: contentX
            ))
        }

        let finalWidth = max(20.0, ceil(cursor))
        let composite = NSImage(size: NSSize(width: finalWidth, height: height))
        composite.lockFocus()
        NSGraphicsContext.current?.imageInterpolation = .high

        for item in placed {
            if let alert = item.alert {
                let color = Self.alertColor(for: alert)
                let outlineRect = NSRect(x: item.outlineX + 0.5, y: 0.5, width: item.outlineWidth - 1, height: height - 1)
                let path = NSBezierPath(roundedRect: outlineRect, xRadius: outlineRadius, yRadius: outlineRadius)
                color.withAlphaComponent(0.18).setFill()
                path.fill()
                color.setStroke()
                path.lineWidth = 1.0
                path.stroke()
            }

            var x = item.contentX

            if let img = item.image, item.imageSize.width > 0 {
                let yOffset = (height - item.imageSize.height) / 2.0
                let rect = NSRect(x: x, y: yOffset, width: item.imageSize.width, height: item.imageSize.height)

                if item.tinted {
                    let tinted = NSImage(size: item.imageSize)
                    tinted.lockFocus()
                    NSGraphicsContext.current?.imageInterpolation = .high
                    NSColor.labelColor.set()
                    let symbolRect = NSRect(origin: .zero, size: item.imageSize)
                    img.draw(in: symbolRect, from: .zero, operation: .sourceOver, fraction: 1.0)
                    symbolRect.fill(using: .sourceIn)
                    tinted.unlockFocus()
                    tinted.draw(in: rect, from: .zero, operation: .sourceOver, fraction: 1.0)
                } else {
                    img.draw(in: rect, from: .zero, operation: .sourceOver, fraction: 1.0)
                }

                x += item.imageSize.width
                if !item.text.isEmpty {
                    x += iconTextGap
                }
            }

            if !item.text.isEmpty {
                let textY = (height - item.textSize.height) / 2.0
                let textRect = NSRect(x: x, y: textY, width: item.textSize.width, height: item.textSize.height)
                (item.text as NSString).draw(in: textRect, withAttributes: textAttrs)
            }
        }

        composite.unlockFocus()
        return composite
    }
}
